CREATE TABLE HORMONE
(
    HM_ID VARCHAR(16) CONSTRAINT NN_HORMONE_ID NOT NULL,
    HM_DOG_ID VARCHAR(16) CONSTRAINT NN_HORMONE_DOG_ID NOT NULL,
    HM_TYPE VARCHAR(32) CONSTRAINT NN_HORMONE_TYPE NOT NULL,
    HM_VALUE NUMERIC(8,3) CONSTRAINT NN_HORMONE_VALUE NOT NULL,
    HM_UNIT VARCHAR(16) CONSTRAINT NN_HORMONE_UNIT NOT NULL,
    HM_STATUS VARCHAR(8) CONSTRAINT NN_HORMONE_STATUS NOT NULL,
    HM_CREATED_TS TIMESTAMP(6) CONSTRAINT NN_HORMONE_CREATED_TS NOT NULL
);

ALTER TABLE HORMONE
    ADD CONSTRAINT PK_HORMONE_ID
        PRIMARY KEY (HM_ID);

ALTER TABLE HORMONE
    ADD CONSTRAINT FK_HORMONE_DOG
        FOREIGN KEY (HM_DOG_ID)
            REFERENCES DOG (DOG_ID);

COMMENT ON TABLE HORMONE IS 'This table stores hormone measurements for a dog.';

COMMENT ON COLUMN HORMONE.HM_ID IS 'The unique identifier for this hormone record.';
COMMENT ON COLUMN HORMONE.HM_DOG_ID IS 'The ID of the dog this hormone entry belongs to.';
COMMENT ON COLUMN HORMONE.HM_TYPE IS 'The type of hormone measured (e.g., TSH, Cortisol, Estrogen, etc.).';
COMMENT ON COLUMN HORMONE.HM_VALUE IS 'The numeric value of the hormone measurement.';
COMMENT ON COLUMN HORMONE.HM_UNIT IS 'The unit of measurement for the hormone value.';
COMMENT ON COLUMN HORMONE.HM_STATUS IS 'The status of the hormone measurement (HI, LO, NORM).';
COMMENT ON COLUMN HORMONE.HM_CREATED_TS IS 'The timestamp when this hormone record was created.';