CREATE TABLE HORMONE
(
    HM_ID VARCHAR(36) CONSTRAINT NN_HM_ID NOT NULL,
    HM_DOG_ID VARCHAR(36) CONSTRAINT NN_HORMONE_DOG_ID NOT NULL,
    HM_TYPE VARCHAR(32) CONSTRAINT NN_TYPE NOT NULL,
    HM_STATUS VARCHAR(8) CONSTRAINT NN_STATUS NOT NULL,
    HM_CREATED_TS TIMESTAMP(6) CONSTRAINT NN_CREATED_TS NOT NULL
);

ALTER TABLE HORMONE
    ADD CONSTRAINT PK_HORMONE_ID
        PRIMARY KEY (HM_ID);

ALTER TABLE HORMONE
    ADD CONSTRAINT FK_HORMONE_DOG
        FOREIGN KEY (HM_DOG_ID)
            REFERENCES DOG (DOG_ID);

COMMENT ON TABLE HORMONE IS 'This table stores hormone quiz results for a given dog.';

COMMENT ON COLUMN HORMONE.HM_ID IS 'The unique identifier for the hormone status record.';
COMMENT ON COLUMN HORMONE.HM_DOG_ID IS 'The ID of the dog the hormone entry belongs to.';
COMMENT ON COLUMN HORMONE.HM_TYPE IS 'The type of hormone group (thyroid, adrenal, pancreatic).';
COMMENT ON COLUMN HORMONE.HM_STATUS IS 'The calculated status from quiz answers (green, yellow, red).';
COMMENT ON COLUMN HORMONE.HM_CREATED_TS IS 'The timestamp when this hormone record was created.';