CREATE TABLE HEART
(
    HT_ID VARCHAR(36) CONSTRAINT NN_HEART_ID NOT NULL,
    HT_DOG_ID VARCHAR(36) CONSTRAINT NN_HEART_DOG_ID NOT NULL,
    HT_FATIGUE BOOLEAN,
    HT_COUGHING BOOLEAN,
    HT_MURMURS VARCHAR(20),
    HT_HEART_RATE NUMERIC(5,2),
    HT_BREATHING_RATE NUMERIC(5,2),
    HT_DIROFILARIA_LAST_PREVENTION DATE,
    HT_CREATED_TS TIMESTAMP(6) CONSTRAINT NN_HEART_CREATED_TS NOT NULL
);

ALTER TABLE HEART
    ADD CONSTRAINT PK_HEART_ID
        PRIMARY KEY (HT_ID);

ALTER TABLE HEART
    ADD CONSTRAINT FK_HEART_DOG
        FOREIGN KEY (HT_DOG_ID)
            REFERENCES DOG (DOG_ID);

COMMENT ON TABLE HEART IS 'This table stores heart health records for a dog.';

COMMENT ON COLUMN HEART.HT_ID IS 'The unique identifier for this heart record.';
COMMENT ON COLUMN HEART.HT_DOG_ID IS 'The ID of the dog this heart entry belongs to.';
COMMENT ON COLUMN HEART.HT_FATIGUE IS 'Boolean flag indicating if the dog tires easily.';
COMMENT ON COLUMN HEART.HT_COUGHING IS 'Boolean flag indicating if the dog has coughing.';
COMMENT ON COLUMN HEART.HT_MURMURS IS 'Heart murmur status: NONE, SOFT, LOUD, SEVERE.';
COMMENT ON COLUMN HEART.HT_HEART_RATE IS 'The resting heart rate in beats per minute.';
COMMENT ON COLUMN HEART.HT_BREATHING_RATE IS 'The breathing rate in breaths per minute.';
COMMENT ON COLUMN HEART.HT_DIROFILARIA_LAST_PREVENTION IS 'The date of the last heartworm prevention treatment.';
COMMENT ON COLUMN HEART.HT_CREATED_TS IS 'The timestamp when this heart record was created.';