CREATE TABLE HEALTH_RECORD
(
    HR_ID VARCHAR(16) CONSTRAINT NN_HEALTH_RECORD_ID NOT NULL,
    HR_DOG_ID VARCHAR(16) CONSTRAINT NN_HEALTH_RECORD_DOG_ID NOT NULL,
    HR_LAST_VET_VISIT_TS TIMESTAMP(6) CONSTRAINT NN_HEALTH_RECORD_LAST_VISIT NOT NULL,
    HR_DOC_TITLE VARCHAR(255) CONSTRAINT NN_HEALTH_RECORD_DOC_TITLE NOT NULL,
    HR_DOC_PATH VARCHAR(500),
    HR_DOC_MIME_TYPE VARCHAR(100),
    HR_CREATED_TS TIMESTAMP(6) CONSTRAINT NN_HEALTH_RECORD_CREATED_TS NOT NULL
);

ALTER TABLE HEALTH_RECORD
    ADD CONSTRAINT PK_HEALTH_RECORD_ID
        PRIMARY KEY (HR_ID);

ALTER TABLE HEALTH_RECORD
    ADD CONSTRAINT FK_HEALTH_RECORD_DOG
        FOREIGN KEY (HR_DOG_ID)
            REFERENCES DOG (DOG_ID);

COMMENT ON TABLE HEALTH_RECORD IS 'This table stores general health records for a dog.';

COMMENT ON COLUMN HEALTH_RECORD.HR_ID IS 'The unique identifier for this health record.';
COMMENT ON COLUMN HEALTH_RECORD.HR_DOG_ID IS 'The ID of the dog this health record belongs to.';
COMMENT ON COLUMN HEALTH_RECORD.HR_LAST_VET_VISIT_TS IS 'Timestamp of the dog’s last veterinary visit.';
COMMENT ON COLUMN HEALTH_RECORD.HR_DOC_TITLE IS 'Title of the uploaded vet document (e.g., Vaccination Certificate).';
COMMENT ON COLUMN HEALTH_RECORD.HR_DOC_PATH IS 'Path or URL where the uploaded document is stored.';
COMMENT ON COLUMN HEALTH_RECORD.HR_DOC_MIME_TYPE IS 'The MIME type of the uploaded file (e.g., application/pdf, image/png).';
COMMENT ON COLUMN HEALTH_RECORD.HR_CREATED_TS IS 'The timestamp when this health record was created.';