CREATE TABLE HEALTH_RECORD
(
    HR_ID VARCHAR(36) CONSTRAINT NN_HM_ID NOT NULL,
    HR_DOG_ID VARCHAR(36) CONSTRAINT NN_HORMONE_DOG_ID NOT NULL,
    HR_DOCUMENT_NAME VARCHAR(255) NOT NULL,
    HR_DOCUMENT_URL VARCHAR(512) NOT NULL,
    HR_CONTENT_TYPE VARCHAR(60) NOT NULL,
    HR_CREATED_TS TIMESTAMP(6) CONSTRAINT NN_CREATED_TS NOT NULL
);

ALTER TABLE HEALTH_RECORD
    ADD CONSTRAINT PK_HEALTH_RECORD_ID
        PRIMARY KEY (HR_ID);

ALTER TABLE HEALTH_RECORD
    ADD CONSTRAINT FK_HEALTH_RECORD_DOG
        FOREIGN KEY (HR_DOG_ID)
            REFERENCES DOG (DOG_ID);

COMMENT ON TABLE HEALTH_RECORD IS 'This table stores health record data file uploads for a given dog.';

COMMENT ON COLUMN HEALTH_RECORD.HR_ID IS 'The unique identifier for the health record.';
COMMENT ON COLUMN HEALTH_RECORD.HR_DOG_ID IS 'The ID of the dog the health record entry belongs to.';
COMMENT ON COLUMN HEALTH_RECORD.HR_DOCUMENT_NAME IS 'The document name.';
COMMENT ON COLUMN HEALTH_RECORD.HR_DOCUMENT_URL IS 'The document url.';
COMMENT ON COLUMN HEALTH_RECORD.HR_CONTENT_TYPE IS 'The document content type.';
COMMENT ON COLUMN HEALTH_RECORD.HR_CREATED_TS IS 'The timestamp of the file upload.';